package com.buildcrm.enums;

public enum ActivityType {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
    EMPLOYEE_ADDED,
    EMPLOYEE_UPDATED,
    MILESTONE_REACHED,
    PAYMENT_RECEIVED,
    EXPENSE_ADDED,
    DOCUMENT_UPLOADED,
    NOTE_ADDED,
    PIPELINE_MOVED,
    USER_LOGIN
}
